const String FAVORITE_SCREEN_OPENED = "FAVORITE_SCREEN_OPENED";
const String FACT_OF_DAY_SCREEN_OPENED = "FACT_OF_DAY_SCREEN_OPENED";
const String RATE_ME_OPENED = "RATE_ME_OPENED";
const String CREDITS_OPENED = "CREDITS_OPENED";

const String NEXT_FACT_TAP = "NEXT_FACT_TAP";
const String FACT_SOURCE_OPENED = "FACT_SOURCE_OPENED";
const String SHARE_BUTTON_CLICKED = "SHARE_BUTTON_CLICKED";
const String FAVORITE_BUTTON_CLICKED = "FAVORITE_BUTTON_CLICKED";
